---
# NOTE(rkm 2021-01-09) Will need to update the new cache tasks for Windows if we decide to use that again
parameters:
    os:
    language:

steps:
    - task: Bash@3
      displayName: Set compose file variable
      inputs:
          targetType: "inline"
          script: |
              set -euxo pipefail
              compose_file=.azure-pipelines/docker-compose/'*'${{ parameters.os }}'*'${{ parameters.language }}'*'.yml
              test -f $compose_file
              echo "##vso[task.setvariable variable=compose_file]$compose_file"
    - task: Bash@3
      displayName: Re-write the compose file with tags from the lockfile
      inputs:
          targetType: "inline"
          script: |
            docker run \
                --rm \
                -v`pwd`/.azure-pipelines/docker-compose:/run \
                --user $(id -u):$(id -g) \
                safewaters/docker-lock \
                    lock rewrite \
                    --lockfile-name $(basename $(compose_file).lock)
    - task: Cache@2
      displayName: Use docker iamges cache
      inputs:
          key: "docker | $(compose_file)"
          path: $(DOCKER_CACHE_DIR)
          cacheHitVar: DOCKER_CACHE_RESTORED
    - task: Bash@3
      displayName: Load docker images if cached
      condition: and(not(canceled()), eq(variables.DOCKER_CACHE_RESTORED, 'true'))
      inputs:
          targetType: "inline"
          script: docker load < $(DOCKER_CACHE_DIR)/cache.tar
    - task: Bash@3
      displayName: Save docker images to cache
      condition: and(not(canceled()), or(failed(), ne(variables.DOCKER_CACHE_RESTORED, 'true')))
      inputs:
          targetType: "inline"
          script: |
            mkdir -p $(DOCKER_CACHE_DIR)
            docker pull ubuntu
            docker save ubuntu > $(Pipeline.Workspace)/docker/cache.tar