---
steps:
    - task: DockerCompose@0
      displayName: Start Linux containers for .NET tests
      inputs:
          containerregistrytype: "Container Registry"
          dockerComposeFile: ".azure-pipelines/docker-compose/linux-java.yml"
          dockerComposeFileArgs: "DB_PASSWORD=$(DB_PASSWORD)"
          action: "Run services"
    - template: ./wait-for.yml
      parameters:
          name: RabbitMQ
          cmd: docker exec rabbitmq rabbitmq-diagnostics -q ping
