---
steps:
    - task: DockerCompose@0
      displayName: Start cross-platform containers for .NET tests
      inputs:
          containerregistrytype: "Container Registry"
          dockerComposeFile: ".azure-pipelines/docker-compose/linux-win-dotnet.yml"
          dockerComposeFileArgs: "DB_PASSWORD=$(DB_PASSWORD)"
          action: "Run services"
    - template: ./wait-for.yml
      parameters:
          name: MongoDB
          cmd: docker exec mongodb bash -c "test "$(/usr/bin/mongo --quiet --eval "db.stats().ok")" -eq 1'
    - template: ./wait-for.yml
      parameters:
          name: MsSQL
          cmd: docker exec mssql bash -c "/opt/mssql-tools/bin/sqlcmd -U sa -P $(DB_PASSWORD) -l 1 -Q "SELECT @@VERSION""
    - template: ./wait-for.yml
      parameters:
          name: Redis
          cmd: docker exec redis bash -c "/usr/local/bin/redis-cli PING"
