---
steps:
  - task: UseDotNet@2
    displayName: Use .NET Core SDK
    inputs:
        packageType: sdk
        version: $(DOTNET_SDK_VERSION)
        installationPath: $(Agent.ToolsDirectory)/dotnet

