---

steps:
  - task: PythonScript@0
    inputs:
      pythonInterpreter: '/usr/bin/python3'
      scriptSource: 'inline'
      script: |
        import json
        vars = json.load(open(".azure-pipelines/vars.json"))
        for k, v in vars.items():
          print(f"##vso[task.setvariable variable={k}]{v}")