---

steps:
  - task: PythonScript@0
    inputs:
      pythonInterpreter: '/usr/bin/python3'
      scriptSource: 'inline'
      script: |
        import json
        import sys

        with open(".azure-pipelines/vars.json") as f:
            vars = json.load(f)

        for k, v in vars.items():
            print(f"##vso[task.setvariable variable={k}]{v}")
            print(f"##vso[task.setvariable variable={k}]{v}", file=sys.stderr)