---
steps:
    - task: PowerShell@2
      displayName: Install RabbitMQ
      inputs:
          targetType: "inline"
          script: choco install rabbitmq
    # TODO password
    # TODO May have to stop the pre-installed MySQL
    - task: PowerShell@2
      displayName: Install MariaDB
      inputs:
          targetType: "inline"
          script: choco install mariadb
    - template: ./wait-for.yml
      parameters:
          name: RabbitMQ
          cmd: rabbitmq-diagnostics -q ping
    - template: ./wait-for.yml
      parameters:
          name: MariaDB
          cmd: mysqladmin -uroot -p$(DB_PASSWORD) status
