---
parameters:
    vmImage:

jobs:
    - job: build_artefacts
      displayName: Build Artefacts
      pool:
          vmImage: ${{ parameters.vmImage }}
    #   condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      dependsOn: [dotnet_tests, java_tests]
      steps:
          - task: Bash@3
            displayName: Install pigz on Linux
            condition: eq('$(Agent.OS)', 'Linux')
            inputs:
                targetType: "inline"
                script: |
                    set -euxo pipefail
                    sudo apt-get update -qq
                    sudo apt-get install -y pigz
          - task: Bash@3
            displayName: Build artefacts
            inputs:
                filePath: .azure-pipelines/scripts/buildArtefacts.py
                arguments: $(Agent.OS) $( echo ${{ variables.Build.SourceBranch }} | cut -d'/' -f3)
          - task: Bash@3
            displayName: List files
            inputs:
                targetType: inline
                script: |
                  find dist -type f