---
steps:
    - task: PowerShell@2
      displayName: Add replication to mongodb config
      inputs:
          targetType: "inline"
          script: 'Add-Content "C:\Program Files\MongoDB\Server\4.4\bin\mongod.cfg" "`r`nreplication:`r`n  replSetName: rs0`r`n"'
    - task: PowerShell@2
      displayName: Restart MongoDB
      inputs:
          targetType: "inline"
          script: Restart-Service -Name MongoDB
