version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  target-branch: master
  reviewers:
  - rkm
  - tznind
  - jas88
- package-ecosystem: maven
  directory: "/src/common/com.smi.microservices.parent"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  target-branch: master
  reviewers:
  - rkm
  - tznind
  - jas88
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - rkm
  - tznind
  - jas88
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: daily
  allow:
    - dependency-type: "all"
