---

trigger:
    branches:
        include: ["*"]
    tags:
        include: ["*"]

jobs:
    - job: run_dotnet_tests
      displayName: Run dotnet tests
      steps:
        - script: ./meta/run_dotnet_tests.sh
    - job: run_java_tests
      displayName: Run java tests
      steps:
        - script: ./meta/run_java_tests.sh
    - job: build_artefacts
      displayName: Upload tagged releases to GitHub
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      dependsOn: [run_dotnet_tests, run_java_tests]
      steps:
        - script: ./meta/build_artefacts.sh $( echo ${{ variables.Build.SourceBranch }} | cut -d'/' -f3)
