
# SMI Services Build Pipeline Configuration

# TODO:
# - Pull & setup containers
# - Fix & enable the tests
# - "dotnet publish" after dotnet tests pass
# - "mvn assembly:single@create-deployable" after Java tests pass

trigger:
  batch: true
  branches:
    include:
    - master
    - develop

pr:
  autoCancel: true
  branches:
    include:
    - master
	- develop

stages:

- stage: Build
  displayName: Build all projects
  jobs:
  - job: BuildDotnet
    displayName: Build - .NET Core Projects
    strategy:
      matrix:
        Linux:
          imageName: 'ubuntu-latest'
        Windows:
          imageName: 'windows-latest'
    pool:
      name: 'Azure Pipelines'
      vmImage: $(imageName)
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: './SmiServices.sln'
  - job: BuildJava
    displayName: Build - Java Projects
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        bash ./installDat.sh
      workingDirectory: ./lib/java
    - task: Maven@3
      displayName: Maven Package
      inputs:
        mavenPomFile: './src/common/com.smi.microservices.parent/pom.xml'
        options: '-DskipTests'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
