version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "live"
    target_branch: "develop"
    default_reviewers:
    - rkm
    - tznind
  - package_manager: "java:maven"
    directory: "/src/common/com.smi.microservices.parent/"
    update_schedule: "daily"
    target_branch: "develop"
    default_reviewers:
    - rkm
    - tznind
