---
trigger:
    branches:
        include:
            - "*"
    tags:
        include:
            - "*"

jobs:
    - template: jobs/test.yml
      parameters:
          vmImage: ubuntu-18.04
    - template: jobs/package.yml
      parameters:
          vmImage: ubuntu-18.04
