---
trigger:
    branches:
        include:
            - "*"
    tags:
        include:
            - "*"

jobs:
    - template: jobs/test.yml
      parameters:
          vmImage: windows-2019
    - template: jobs/package.yml
      parameters:
          vmImage: windows-2019
