---
name: SmiServices Windows test

trigger:
    branches:
        include:
            - "*"
    tags:
        include:
            - "*"

variables:
    CI: 1
    NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
    MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
    MAVEN_OPTS: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)"
    RDMP_CLI_DIR: $(Pipeline.Workspace)/rdmp-cli
    TESS_DATA_DIR: $(Pipeline.Workspace)/tessdata
    DB_PASSWORD: "YourStrongPassw0rd"

jobs:
    - template: jobs/tests.yml
      parameters:
          vmImage: windows-2019
          os: win
    - template: jobs/package.yml
      parameters:
          vmImage: windows-2019
          os: win
